### ISSUE TITLE
Create ZendDiagnostics website

### ISSUE THREAD

**Issue by Thinkscape** [zendframework/zend-diagnostics#33]
I'd like to have a website explaining the benefits and best practices for production apps' diagnostics suite.

It would also include usage examples for various frameworks and a catalog of available checks.

**Comment by seyfer** [comment]
:+1:

**Comment by weierophinney** [comment]
I've separated the README.md file into discrete markdown documentation pages, and added a webhook to build and publish the docs to https://docs.zendframework.com/zend-diagnostics/ 

If folks want to add more, add to the docs (which is under the `docs/book/` tree.
