### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-diagnostics#77]
Without this file, redistribution of this library in any project will be impossible with violating the BSD license term:

```
* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
```

Also see: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text

**Comment by llaville** [comment]
At authors of ZendDignostics package, please have a look on this request. Without license file, i cannot release my own packages using this one. And i don't want to think to let down this cool feature.
Thanks in advance

**Comment by llaville** [comment]
This package seems to be not maintained anymore. I'll have, with regret, to decide to not use it.

**Comment by snapshotpl** [comment]
@Thinkscape ping

**Comment by llaville** [comment]
@Thinkscape ping / one regret : to see the new release without the LICENSE file

**Comment by weierophinney** [comment]
Done with #89 ; will have in the next release (which should be today).
