### ISSUE TITLE
There needs to be an exit code for CI purposes

### ISSUE THREAD

**Issue by alesanchezr** [zendframework/zend-diagnostics#86]
https://github.com/zendframework/ZendDiagnostics/blob/d27aa064c5185c5830e917ffe48284b0995eed13/src/ZendDiagnostics/Runner/Reporter/BasicConsole.php#L254

https://www.perpetual-beta.org/weblog/php-from-the-command-line.html#exit-codes

**Comment by weierophinney** [comment]
This really has to be in whatever script is executing the runner. If we do it in the `BasicConsole`, we may exit prematurely.

I will document how to do this when running a vanilla PHP diagnostic script using the `BasicConsole`, but beyond that, it's up to projects shipping console scripts that exercise a runner to emit the correct exit code.
