### ISSUE TITLE
Rename repository to zend-diagnostics (with dash)

### ISSUE THREAD

**Issue by webimpress** [zendframework/zend-diagnostics#99]
Currently the repository name is: `zendframework/zenddiagnostics`.
Can we rename it to `zendframework/zend-diagnostics` (with dash) to match naming convention in ZF repo names?

See:
- https://packagist.org/packages/zendframework/zenddiagnostics

https://github.com/zendframework/zend-diagnostics/blob/94e743e760444800ca44522a9673264a1149dfab/composer.json#L2

**Comment by weierophinney** [comment]
Already done!
